name: Docker Image CI

on:
  release:
    branches: [ migrations-tools ]    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ferras1/metadata_service
          tag_with_ref: true
          tag_with_sha: true
          tags: "latest"
          dockerfile: ${{ github.workspace }}/Dockerfile
